import { useEffect,useMemo,useState } from 'react'
import { BookOpen, Library, Search, FolderPlus, Heart, Target, BarChart3, Settings, Play, Plus, Moon, Sun, Timer, Copy, NotebookPen, Trash2 } from 'lucide-react'
import { useApp } from './store'
import type { Book } from './types'
import { Reader } from './Reader'

type View='home'|'all'|'unread'|'in-progress'|'finished'|'favorites'|'collections'|'notes'|'duplicates'|'stats'|'settings'
const labels:Record<View,string>={home:'Home',all:'All books',unread:'Unread','in-progress':'In progress',finished:'Finished',favorites:'Favorites',collections:'Collections',notes:'Notes & marks',duplicates:'Duplicates',stats:'Reading stats',settings:'Settings'}
function BookCard({book,onOpen}:{book:Book,onOpen:()=>void}){const patch=useApp(s=>s.patchBook);return <article className="book-card"><button className="cover" onClick={onOpen}><span>{book.format.toUpperCase()}</span><BookOpen size={34}/></button><div className="book-meta"><button className="title" onClick={onOpen}>{book.title}</button><p>{book.author}</p><div className="progress"><i style={{width:`${book.progress}%`}}/></div><small>{Math.round(book.progress)}% read</small></div><button className={`icon ${book.favorite?'active':''}`} aria-label="Favorite" onClick={()=>patch(book.id,{favorite:!book.favorite})}><Heart size={17}/></button></article>}
function TimerWidget(){const[secs,setSecs]=useState(0);const[on,setOn]=useState(false);useEffect(()=>{if(!on)return;const i=setInterval(()=>setSecs(x=>x+1),1000);return()=>clearInterval(i)},[on]);return <div className="timer"><Timer size={18}/><b>{String(Math.floor(secs/60)).padStart(2,'0')}:{String(secs%60).padStart(2,'0')}</b><button onClick={()=>setOn(!on)}>{on?'Pause':'Focus'}</button></div>}
export default function App(){const s=useApp();const[view,setView]=useState<View>('home');const[q,setQ]=useState('');const[sort,setSort]=useState('recent');const[reading,setReading]=useState<Book|null>(null);useEffect(()=>{s.refresh();return window.readlocal.onLibraryChanged(()=>s.refresh())},[]);useEffect(()=>{document.documentElement.dataset.theme=s.settings.theme},[s.settings.theme]);
const books=useMemo(()=>{let x=[...s.books];if(['unread','in-progress','finished'].includes(view))x=x.filter(b=>b.status===view);if(view==='favorites')x=x.filter(b=>b.favorite);if(view==='duplicates')x=x.filter(b=>b.duplicateGroup);if(q)x=x.filter(b=>(b.title+' '+b.author+' '+b.path).toLowerCase().includes(q.toLowerCase()));x.sort(sort==='title'?(a,b)=>a.title.localeCompare(b.title):(a,b)=>(b.lastOpenedAt||b.addedAt).localeCompare(a.lastOpenedAt||a.addedAt));return x},[s.books,view,q,sort]);
async function addFolder(){const f=await window.readlocal.chooseFolder();if(!f)return;await window.readlocal.scanFolders([...new Set([...s.settings.folders,f])]);await s.refresh()}
async function rescan(){await window.readlocal.scanFolders(s.settings.folders);await s.refresh()}
const today=new Date().toDateString(),todayMins=Math.round(s.sessions.filter(x=>new Date(x.startedAt).toDateString()===today).reduce((a,x)=>a+x.minutes,0));const focus=s.settings.focusShelf.map(id=>s.books.find(b=>b.id===id)).filter(Boolean) as Book[];
if(reading)return <Reader book={reading} onClose={()=>{setReading(null);s.refresh()}}/>;
  return <div className="shell"><aside><div className="brand"><span>R</span><b>ReadLocal <em>V2</em></b></div><nav>{([['home',BookOpen],['all',Library],['unread',Play],['in-progress',Target],['finished',BookOpen],['favorites',Heart],['collections',Plus],['notes',NotebookPen],['duplicates',Copy],['stats',BarChart3],['settings',Settings]] as [View,any][]).map(([v,I])=><button className={view===v?'selected':''} onClick={()=>setView(v)} key={v}><I size={18}/>{labels[v]}</button>)}</nav><div className="privacy">Offline by design<br/><small>Your books never leave this device.</small></div></aside><main><header><div><h1>{labels[view]}</h1><p>{view==='home'?'A calm place to keep your reading moving.':view==='notes'?'Everything you saved while reading.':`${books.length} books`}</p></div><TimerWidget/><button className="primary" onClick={addFolder}><FolderPlus size={17}/> Add folder</button></header>
  {view==='home'?<><section className="hero"><div><small>TODAY'S READING</small><h2>{todayMins} of {s.settings.dailyGoalMinutes} minutes</h2><div className="goal"><i style={{width:`${Math.min(100,todayMins/s.settings.dailyGoalMinutes*100)}%`}}/></div></div><Target size={48}/></section><Section title="Continue reading" books={s.books.filter(b=>b.status==='in-progress').sort((a,b)=>(b.lastOpenedAt||'').localeCompare(a.lastOpenedAt||'')).slice(0,4)} open={setReading}/><Section title={`Focus shelf · ${focus.length}/${s.settings.focusShelfLimit}`} books={focus} open={setReading}/><Section title="Recently added" books={[...s.books].sort((a,b)=>b.addedAt.localeCompare(a.addedAt)).slice(0,4)} open={setReading}/></>:view==='stats'?<Stats/>:view==='settings'?<SettingsView addFolder={addFolder} rescan={rescan}/>:view==='collections'?<Collections open={setReading}/>:view==='notes'?<Annotations open={setReading}/>:<><div className="toolbar"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, author, or path"/></label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently opened</option><option value="title">Title A–Z</option></select></div>{view==='duplicates'&&books.length>0&&<p className="notice">Matching files are grouped by a privacy-safe local content fingerprint. ReadLocal never uploads file contents.</p>}<div className="grid">{books.map(b=><BookCard key={b.id} book={b} onOpen={()=>setReading(b)}/>)}</div>{!books.length&&<Empty add={addFolder}/>}</>}</main></div>}
function Section({title,books,open}:{title:string,books:Book[],open:(b:Book)=>void}){return <section><h2 className="section-title">{title}</h2>{books.length?<div className="grid">{books.map(b=><BookCard key={b.id} book={b} onOpen={()=>open(b)}/>)}</div>:<p className="muted">Nothing here yet.</p>}</section>}
function Empty({add}:{add:()=>void}){return <div className="empty"><BookOpen size={54}/><h2>Build your private library</h2><p>Choose a folder containing PDF or EPUB books. Files stay exactly where they are.</p><button className="primary" onClick={add}><FolderPlus size={17}/> Choose a book folder</button></div>}
function Stats(){const{books,sessions}=useApp();const mins=Math.round(sessions.reduce((a,x)=>a+x.minutes,0));return <div className="stat-grid"><div><b>{books.filter(b=>b.status==='finished').length}</b><span>Books finished</span></div><div><b>{mins}</b><span>Minutes read</span></div><div><b>{sessions.length}</b><span>Focus sessions</span></div><div><b>{books.filter(b=>b.status==='in-progress').length}</b><span>In progress</span></div></div>}
function Collections({open}:{open:(b:Book)=>void}){const s=useApp();const[name,setName]=useState('');async function create(){if(!name.trim())return;await window.readlocal.addCollection(name.trim());setName('');s.refresh()}async function toggle(book:Book,id:string){await s.patchBook(book.id,{collectionIds:book.collectionIds.includes(id)?book.collectionIds.filter(x=>x!==id):[...book.collectionIds,id]})}return <div className="collection-page"><div className="create-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New collection name"/><button className="primary" onClick={create}><Plus size={16}/> Create</button></div>{s.collections.map(c=><section className="collection" key={c.id}><div className="collection-heading"><h2>{c.name}</h2><button onClick={async()=>{await window.readlocal.removeCollection(c.id);s.refresh()}}><Trash2 size={16}/></button></div><div className="collection-books">{s.books.map(b=><label key={b.id}><input type="checkbox" checked={b.collectionIds.includes(c.id)} onChange={()=>toggle(b,c.id)}/><button onClick={()=>open(b)}>{b.title}</button></label>)}</div></section>)}{!s.collections.length&&<p className="muted">Create a collection, then choose which books belong to it.</p>}</div>}
function Annotations({open}:{open:(b:Book)=>void}){const s=useApp();const items=[...s.bookmarks.map(x=>({...x,kind:'Bookmark',text:x.label})),...s.notes.map(x=>({...x,kind:'Note'})),...s.highlights.map(x=>({...x,kind:'Highlight'}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));async function remove(x:any){if(x.kind==='Bookmark')await window.readlocal.removeBookmark(x.id);if(x.kind==='Note')await window.readlocal.removeNote(x.id);if(x.kind==='Highlight')await window.readlocal.removeHighlight(x.id);s.refresh()}return <div className="annotation-list">{items.map(x=>{const book=s.books.find(b=>b.id===x.bookId);return <article key={x.id}><small>{x.kind} · {new Date(x.createdAt).toLocaleDateString()}</small><p>{x.text}</p><button onClick={()=>book&&open(book)}>{book?.title||'Missing book'}</button><button className="delete" onClick={()=>remove(x)}><Trash2 size={15}/></button></article>})}{!items.length&&<p className="muted">Bookmarks, notes, and highlights will appear here.</p>}</div>}
function SettingsView({addFolder,rescan}:{addFolder:()=>void,rescan:()=>void}){const{settings,patchSettings}=useApp();return <div className="settings"><h2>Library folders</h2>{settings.folders.map(f=><code key={f}>{f}</code>)}<div><button onClick={addFolder}>Add folder</button> <button onClick={rescan}>Rescan library</button></div><h2>Reading</h2><label>Daily goal <input type="number" min="5" value={settings.dailyGoalMinutes} onChange={e=>patchSettings({dailyGoalMinutes:+e.target.value})}/> minutes</label><label>Focus shelf limit <input type="number" min="1" max="7" value={settings.focusShelfLimit} onChange={e=>patchSettings({focusShelfLimit:+e.target.value})}/></label><h2>Appearance</h2><div className="themes">{(['light','sepia','dark'] as const).map(t=><button className={settings.theme===t?'chosen':''} onClick={()=>patchSettings({theme:t})} key={t}>{t==='dark'?<Moon/>:<Sun/>}{t}</button>)}</div></div>}
