import { useEffect,useRef,useState } from 'react'
import ePub from 'epubjs'
import { ArrowLeft, Bookmark, Maximize, Minimize, Minus, Plus, StickyNote, Target, Highlighter, ChevronLeft, ChevronRight } from 'lucide-react'
import type { Book } from './types';import{useApp}from'./store'
import { PdfReader } from './PdfReader'
export function Reader({book,onClose}:{book:Book,onClose:()=>void}){const patch=useApp(s=>s.patchBook),settings=useApp(s=>s.settings),refresh=useApp(s=>s.refresh);const[full,setFull]=useState(false),[font,setFont]=useState(100),[url,setUrl]=useState(''),[position,setPosition]=useState(book.position||''),[note,setNote]=useState(''),[selection,setSelection]=useState<{cfi:string;text:string}|null>(null);const mount=useRef<HTMLDivElement>(null),started=useRef(Date.now()),rendition=useRef<any>();
useEffect(()=>{window.readlocal.fileUrl(book.path).then(setUrl);patch(book.id,{lastOpenedAt:new Date().toISOString(),status:book.status==='unread'?'in-progress':book.status});return()=>{const minutes=Math.max(1,Math.round((Date.now()-started.current)/60000));window.readlocal.logSession({bookId:book.id,startedAt:new Date(started.current).toISOString(),endedAt:new Date().toISOString(),minutes})}},[])
useEffect(()=>{if(book.format!=='epub'||!url||!mount.current)return;const bk=ePub(url);const r=bk.renderTo(mount.current,{width:'100%',height:'100%',spread:'auto'});rendition.current=r;r.display(position||undefined);r.themes.fontSize(`${font}%`);r.on('relocated',(loc:any)=>{const p=loc.start.cfi,progress=Math.round((bk.locations.percentageFromCfi(p)||0)*100);setPosition(p);patch(book.id,{position:p,progress,status:progress>=99?'finished':'in-progress'})});r.on('selected',(cfi:string,contents:any)=>{const text=contents.window.getSelection()?.toString().trim();if(text)setSelection({cfi,text})});bk.ready.then(()=>bk.locations.generate(1200));return()=>{r.destroy();bk.destroy()}},[url])
useEffect(()=>{rendition.current?.themes.fontSize(`${font}%`)},[font]);async function mark(){await window.readlocal.addBookmark({bookId:book.id,position,label:`${Math.round(book.progress)}%`});await refresh()}async function saveNote(){if(!note.trim())return;await window.readlocal.addNote({bookId:book.id,position,text:note.trim()});setNote('');await refresh()}function pdfPosition(page:number,total:number){const progress=Math.round(page/total*100);setPosition(String(page));patch(book.id,{pageCount:total,progress,position:String(page),status:page>=total?'finished':'in-progress'})}
const inFocus=settings.focusShelf.includes(book.id);async function focus(){const next=inFocus?settings.focusShelf.filter(x=>x!==book.id):settings.focusShelf.length<settings.focusShelfLimit?[...settings.focusShelf,book.id]:settings.focusShelf;await window.readlocal.saveSettings({focusShelf:next});refresh()}
async function highlight(){if(!selection)return;await window.readlocal.addHighlight({bookId:book.id,position:selection.cfi,text:selection.text,color:'amber'});rendition.current?.annotations.highlight(selection.cfi,{},undefined,'readlocal-highlight');setSelection(null);refresh()}
return <div className={`reader ${full?'fullscreen':''}`}><header><button onClick={onClose}><ArrowLeft/> Library</button><div><b>{book.title}</b><small>{book.author}</small></div><div className="reader-actions">{book.format==='epub'&&<><button title="Previous" onClick={()=>rendition.current?.prev()}><ChevronLeft/></button><button title="Next" onClick={()=>rendition.current?.next()}><ChevronRight/></button></>}<button title="Focus shelf" onClick={focus} className={inFocus?'active':''}><Target/></button><button title="Bookmark" onClick={mark}><Bookmark/></button>{book.format==='epub'&&<><button onClick={()=>setFont(Math.max(70,font-10))}><Minus/></button><span>{font}%</span><button onClick={()=>setFont(Math.min(180,font+10))}><Plus/></button></>}<button onClick={()=>setFull(!full)}>{full?<Minimize/>:<Maximize/>}</button></div></header><div className="reader-body"><div className="page">{book.format==='pdf'&&url?<PdfReader url={url} initialPage={Number(book.position)||1} onPosition={pdfPosition}/>:<div ref={mount} className="epub"/>}{selection&&<button className="selection-action" onClick={highlight}><Highlighter size={16}/> Highlight selection</button>}</div><aside><h3><StickyNote/> Reading note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Capture a thought at this position…"/><button onClick={saveNote}>Save note</button><p className="hint">Position, page, progress, and reading status save automatically.</p></aside></div></div>}
